server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka3:8763/eureka/

spring:
  application:
    name: eureka-server
  